services:
  - type: web
    name: smartnotes
    runtime: docker
    repo: https://github.com/AhmadAlhitmi/projectINFS3203
    branch: main
    plan: free
    healthCheckPath: /health
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
